services:
  issuance:
    build: ./kube-issuance
    image: kube-issuance
    container_name: kube-issuance
    env_file:
      - ./kube-issuance/.env
    environment:
      - WORKER_ID=issuance-worker
      - DATABASE_URL=file:./dev.db
      - PORT=3001
    ports:
      - '3001:3001'

  verification:
    build: ./kube-verification
    image: kube-verification
    container_name: kube-verification
    env_file:
      - ./kube-verification/.env
    environment:
      - WORKER_ID=verification-worker
      - DATABASE_URL=file:./verify.db
      - PORT=4001
      - ISSUANCE_URL=http://issuance:3000
    ports:
      - '4001:4001'
    depends_on:
      - issuance

  frontend:
    build: ./kube-frontend
    image: kube-frontend
    container_name: kube-frontend
    ports:
      - '5173:80'
    depends_on:
      - issuance
      - verification
